normalized license headers (#143)
* normalized license headers
* added linting for license headers runs on checkin
* fixed racy behavior in CLI logging starting scanning of content prior to start

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -7,6 +7,15 @@ set -e
 
 cd "$(dirname "$0")/.."
 
+echo "Checking if license-header-checker is installed"
+date "+%H:%M:%S"
+
+if ! type "license-header-checker" > /dev/null; then
+  echo "license-header-checker not found installing.."
+  date "+%H:%M:%S"
+  curl -s https://raw.githubusercontent.com/lluissm/license-header-checker/master/install.sh | bash
+fi
+
 echo "Checking if golangci-lint is installed…"
 date "+%H:%M:%S"
 
